base: CHANGELOG.md
future-release: 
add_pr_wo_labels: true
exclude_labels:
  - duplicate
  - question
  - invalid
  - wontfix
  - dependencies
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'maintenance'
