"""Prototype for #1117: over_time history + regression views on named timelines.

Answers, by building one real recording:

A. **History as a TIME channel assignment.** A real bencher ``over_time=True``
   benchmark (``batch_size`` sweep x 5 repeats) is run 8 times with wall-clock
   ``time_src`` datetimes; the merged history dataset (dims
   ``batch_size x repeat x over_time``, ``over_time`` = datetime64 coords) is
   lowered to rerun with ``rr.set_time("over_time", timestamp=...)`` — a named
   *timestamp-typed* timeline. The per-run ±sigma spread (from ``repeat``) is
   lowered per the #1110 Spread ruling's single-series form: three SeriesLines
   (mean full-color w=2.5, ±1sigma edges lighter tint w=0.75). The second sweep
   dim ``batch_size`` coexists both as FACET_COL (one view per value) and as
   its *own named timeline* (the current run's sweep curve indexed on a
   ``batch_size`` sequence timeline) in the same recording.

B. **Regression views.** ``detect_regressions`` (the real bencher machinery,
   run by ``plot_sweep`` itself) supplies the comparison; its rerun form is an
   OVERLAY on the history timeline: history-mean line + baseline (reference)
   line + acceptance-band edge lines + verdict-coloured current point. The
   pass/fail-over-history mark is built three ways to decide by looking:
     (a) a 0/1 SeriesLines in its own view,
     (b) SeriesPoints riding the history-mean value with per-timestep
         red/green colours,
     (c) a TextLog verdict stream on the same timeline.
   Verdicts are honest replays: ``detect_regressions`` re-run on every
   history prefix ``ds.isel(over_time=slice(0, t+1))``.

C. **Report-wide timeline sharing.** Two result vars' histories land under
   host-assigned prefixes ``/item_0`` (train_time) and ``/item_1`` (accuracy).
   Both log onto the same ``over_time`` timeline name, so they share one axis
   and one scrubber by construction. A blueprint pins the layout (facet row +
   two-history row + regression row); a second copy of the same data is saved
   *without* a blueprint to see what the viewer selects by default.

Run:
    pixi run python plans/prototypes/history_regression_1117/history_regression.py

Outputs (gitignored, regenerated by this script):
    out/history_regression.rrd              data + blueprint
    out/history_regression_noblueprint.rrd  same data, no blueprint
"""

from __future__ import annotations

import random
import sys
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np

import bencher as bn
from bencher.regression import detect_regressions

PROTO_DIR = Path(__file__).resolve().parent
OUT_DIR = PROTO_DIR / "out"

N_RUNS = 8
BASE_TIME = datetime(2026, 7, 30, 12, 0, 0)
TIMESTAMPS = [BASE_TIME + timedelta(days=i) for i in range(N_RUNS)]

# Per-run performance profile: runs 0..6 carry mild sub-threshold drift; run 7
# is a +30% train_time step (fires the 10% percentage gate on a minimize var)
# and a -6.5% accuracy dip (does NOT fire the gate on a maximize var) — so the
# recording shows one regressed and one passing variable.
TRAIN_PROFILE = [1.0 + 0.005 * i for i in range(N_RUNS - 1)] + [1.30]
ACC_PROFILE = [0.0] * (N_RUNS - 1) + [-0.06]

BLUE, BLUE_TINT = (31, 119, 180), (158, 202, 225)
ORANGE, ORANGE_TINT = (255, 127, 14), (253, 208, 162)
GREY = (120, 120, 120)
GREEN, RED = (44, 160, 44), (214, 39, 40)


class TrainBenchmark(bn.ParametrizedSweep):
    """Synthetic training benchmark: train_time and accuracy vs batch_size."""

    batch_size = bn.IntSweep(default=16, bounds=[16, 64], samples=3, doc="Batch size")

    train_time = bn.ResultFloat(units="s", doc="epoch time", direction=bn.OptDir.minimize)
    accuracy = bn.ResultFloat(units="frac", doc="val accuracy", direction=bn.OptDir.maximize)

    _run_idx = 0  # set externally per over-time snapshot

    def benchmark(self):
        base = 0.8 + 0.004 * self.batch_size
        self.train_time = base * TRAIN_PROFILE[self._run_idx] * random.gauss(1.0, 0.03)
        self.accuracy = (
            0.92 - 0.0004 * self.batch_size + ACC_PROFILE[self._run_idx] + random.gauss(0, 0.004)
        )


def run_history() -> bn.BenchResult:
    """Run the real over_time machinery N_RUNS times; return the final result."""
    random.seed(31117)
    run_cfg = bn.BenchRunCfg(
        over_time=True,
        repeats=5,
        regression_detection=True,
        regression_method="percentage",
        regression_percentage=10.0,
        auto_plot=False,
        run_tag="proto_1117",
    )
    benchable = TrainBenchmark()
    bench = benchable.to_bench(run_cfg)
    res = None
    for i, ts in enumerate(TIMESTAMPS):
        TrainBenchmark._run_idx = i
        run_cfg.clear_cache = True
        run_cfg.clear_history = i == 0
        res = bench.plot_sweep(
            "history_regression_1117",
            input_vars=["batch_size"],
            result_vars=["train_time", "accuracy"],
            run_cfg=run_cfg,
            time_src=ts,
        )
    return res


def replay_verdicts(res: bn.BenchResult) -> dict[str, list[tuple[int, bool, str]]]:
    """Honest pass/fail-over-history: re-run detect_regressions on every prefix.

    Returns {var: [(t_index, regressed, detail), ...]} for t >= 1 (a prefix of
    length 2 is the first with any history to compare against).
    """
    verdicts: dict[str, list[tuple[int, bool, str]]] = {}
    n = res.ds.sizes["over_time"]
    for t in range(1, n):
        sub = res.ds.isel(over_time=slice(0, t + 1))
        report = detect_regressions(sub, res.bench_cfg, res.bench_cfg)
        for r in report.results:
            verdicts.setdefault(r.variable, []).append((t, bool(r.regressed), r.details))
    return verdicts


def _static_line(rr, path: str, color, width: float, name: str) -> None:
    rr.log(path, rr.SeriesLines(colors=[color], widths=width, names=name), static=True)


def log_recording(res: bn.BenchResult, verdicts, path: Path, blueprint_mode: str) -> list[str]:
    """Lower the history dataset + regression report into one .rrd; return notes.

    blueprint_mode: "report" (full pinned layout), "sweep" (active timeline =
    batch_size, sweep view only), or "none" (no blueprint — viewer default).
    """
    import rerun as rr
    import rerun.blueprint as rrb

    notes: list[str] = []
    ds = res.ds
    times = ds["over_time"].values  # np.datetime64[ns]
    batches = [int(b) for b in ds["batch_size"].values]

    rr.init("bencher_1117", recording_id=f"proto_1117_{blueprint_mode}")
    rr.save(str(path))

    # --- A. history as TIME: named timestamp timeline + #1110 spread form -----
    items = {"item_0": "train_time", "item_1": "accuracy"}
    tints = {"item_0": (BLUE, BLUE_TINT), "item_1": (ORANGE, ORANGE_TINT)}
    for item, var in items.items():
        color, tint = tints[item]
        for b in batches:
            base = f"/{item}/batch_size={b}"
            _static_line(rr, f"{base}/mean", color, 2.5, f"{var} mean b={b}")
            _static_line(rr, f"{base}/hi", tint, 0.75, "+1σ")
            _static_line(rr, f"{base}/lo", tint, 0.75, "-1σ")
        da = ds[var]
        for ti, t in enumerate(times):
            rr.set_time("over_time", timestamp=t)
            for b in batches:
                vals = da.sel(batch_size=b).isel(over_time=ti).values.astype(float)
                mean, sigma = float(np.nanmean(vals)), float(np.nanstd(vals))
                base = f"/{item}/batch_size={b}"
                rr.log(f"{base}/mean", rr.Scalars(mean))
                rr.log(f"{base}/hi", rr.Scalars(mean + sigma))
                rr.log(f"{base}/lo", rr.Scalars(mean - sigma))

    # --- A(3). the sweep dim as its OWN named timeline, coexisting -----------
    # The current run's train_time-vs-batch_size curve, indexed on a
    # `batch_size` sequence timeline (NOT on over_time): rr.reset_time() first
    # so these rows carry only the sweep timeline.
    rr.reset_time()
    _static_line(rr, "/item_0/sweep/train_time_vs_batch", BLUE, 2.0, "train_time (latest run)")
    da_last = ds["train_time"].isel(over_time=-1)
    for b in batches:
        rr.set_time("batch_size", sequence=b)
        rr.log(
            "/item_0/sweep/train_time_vs_batch",
            rr.Scalars(float(np.nanmean(da_last.sel(batch_size=b).values.astype(float)))),
        )
    rr.reset_time()

    # --- B. regression views ---------------------------------------------------
    # Real RegressionResult from the run (percentage method, threshold 10%).
    reg = {r.variable: r for r in res.regression_report.results}
    r = reg["train_time"]
    notes.append(
        f"regression train_time: regressed={r.regressed} baseline={r.baseline_value:.4g} "
        f"current={r.current_value:.4g} change={r.change_percent:+.1f}% "
        f"band=({r.band_lower:.4g},{r.band_upper:.4g})"
    )
    ra = reg.get("accuracy")
    if ra is not None:
        notes.append(
            f"regression accuracy: regressed={ra.regressed} change={ra.change_percent:+.1f}%"
        )

    ov = "/item_2/overlay"
    _static_line(rr, f"{ov}/history_mean", BLUE, 2.0, "history mean")
    _static_line(rr, f"{ov}/baseline", GREY, 1.5, f"baseline={r.baseline_value:.3g}")
    _static_line(rr, f"{ov}/band_hi", GREEN, 0.75, "acceptance hi")
    _static_line(rr, f"{ov}/band_lo", GREEN, 0.75, "acceptance lo")
    hist_x = np.asarray(r.historical_x)
    hist_y = np.asarray(r.historical, dtype=float)
    for t, y in zip(hist_x, hist_y):
        rr.set_time("over_time", timestamp=t)
        rr.log(f"{ov}/history_mean", rr.Scalars(float(y)))
        rr.log(f"{ov}/baseline", rr.Scalars(float(r.baseline_value)))
        rr.log(f"{ov}/band_hi", rr.Scalars(float(r.band_upper)))
        rr.log(f"{ov}/band_lo", rr.Scalars(float(r.band_lower)))
    # Extend reference/band to the current timestamp, then the verdict point.
    rr.set_time("over_time", timestamp=np.datetime64(r.current_x))
    rr.log(f"{ov}/baseline", rr.Scalars(float(r.baseline_value)))
    rr.log(f"{ov}/band_hi", rr.Scalars(float(r.band_upper)))
    rr.log(f"{ov}/band_lo", rr.Scalars(float(r.band_lower)))
    verdict_color = RED if r.regressed else GREEN
    rr.log(
        f"{ov}/current",
        rr.SeriesPoints(
            colors=[verdict_color], marker_sizes=6.0, markers="circle", names="current"
        ),
        static=True,
    )
    rr.log(f"{ov}/current", rr.Scalars(float(r.current_value)))

    # Pass/fail-over-history: three candidate marks from the replayed verdicts.
    vlist = verdicts["train_time"]
    # (a) 0/1 line in its own view.
    _static_line(rr, "/item_2/passfail/verdict", GREY, 2.0, "pass=1 / fail=0")
    # (b) verdict-coloured points riding the history-mean value.
    means_by_t = {ti: float(v) for ti, v in zip(range(1, len(times)), list(hist_y[1:]) + [np.nan])}
    # history means exclude the current run; replay verdict at t uses point t as
    # "current", so the y value for candidate (b) is the per-time mean at t.
    da_tt = ds["train_time"]
    for t, regressed, detail in vlist:
        rr.set_time("over_time", timestamp=times[t])
        rr.log("/item_2/passfail/verdict", rr.Scalars(0.0 if regressed else 1.0))
        y_t = float(da_tt.isel(over_time=t).mean(skipna=True).values)
        rr.log(
            "/item_2/points/verdict_on_value",
            rr.SeriesPoints(
                colors=[RED if regressed else GREEN],
                marker_sizes=5.0,
                markers="circle",
                names="verdict",
            ),
        )
        rr.log("/item_2/points/verdict_on_value", rr.Scalars(y_t))
        # (c) TextLog event stream.
        rr.log(
            "/item_2/events",
            rr.TextLog(
                f"train_time {'FAIL' if regressed else 'PASS'} @ {str(times[t])[:19]}: {detail}",
                level="ERROR" if regressed else "INFO",
            ),
        )
    _ = means_by_t  # candidate (b) uses the true per-time mean above

    # --- C. blueprint ------------------------------------------------------------
    # FINDING (pinned here): a TimeSeriesView's default x-axis view does NOT
    # fit a sparse timestamp timeline (it opened on a ~1-minute window around
    # the cursor, flattening 7 days of history) — the blueprint must pin the
    # x-axis view range per view via axis_x=TimeAxis(view_range=(-inf, +inf))
    # (NOT time_ranges=VisibleTimeRanges, which controls per-cursor visible
    # history, not axis zoom — tested: it has no effect on the axis). And the
    # x-axis timeline of every view is the viewer's single ACTIVE timeline
    # (rrb.TimeAxis has no timeline selector in 0.35), so the blueprint also
    # pins TimePanel(timeline=...).
    from rerun import datatypes as rdt

    # Absolute bounds with half-day margins: an infinite view range puts the
    # last sample exactly on the right plot edge, half-clipping the current /
    # FAIL verdict marks.
    margin_ns = int(12 * 3600 * 1e9)
    t0_ns = int(times[0].astype("datetime64[ns]").astype("int64")) - margin_ns
    t1_ns = int(times[-1].astype("datetime64[ns]").astype("int64")) + margin_ns
    full_axis = rrb.TimeAxis(
        view_range=rdt.TimeRange(
            start=rrb.TimeRangeBoundary.absolute(nanos=t0_ns),
            end=rrb.TimeRangeBoundary.absolute(nanos=t1_ns),
        )
    )

    def ts_view(origin: str, name: str) -> rrb.TimeSeriesView:
        return rrb.TimeSeriesView(origin=origin, name=name, axis_x=full_axis)

    if blueprint_mode == "report":
        facet_row = rrb.Horizontal(
            *[ts_view(f"/item_0/batch_size={b}", f"train_time b={b} (±1σ)") for b in batches],
            name="item_0: train_time history, FACET_COL over batch_size",
        )
        histories_row = rrb.Horizontal(
            ts_view("/item_1", "item_1: accuracy history (all batches)"),
            rrb.TimeSeriesView(
                origin="/item_2/overlay",
                name="regression: current vs reference",
                axis_x=full_axis,
                axis_y=rrb.ScalarAxis(range=(0.82, 1.32)),
            ),
            name="second history + regression overlay",
        )
        regression_row = rrb.Horizontal(
            ts_view("/item_2/passfail", "pass/fail 0/1"),
            rrb.TimeSeriesView(
                origin="/item_2/points",
                name="verdict points",
                axis_x=full_axis,
                axis_y=rrb.ScalarAxis(range=(0.85, 1.32)),
            ),
            rrb.TextLogView(origin="/item_2/events", name="verdict events"),
            name="pass/fail-over-history candidates",
        )
        bp = rrb.Blueprint(
            rrb.Vertical(facet_row, histories_row, regression_row),
            rrb.TimePanel(timeline="over_time"),
            collapse_panels=True,
        )
        rr.send_blueprint(bp)
    elif blueprint_mode == "sweep":
        # The sweep dim as its own timeline is a MODE SWITCH, not a coexisting
        # pane: this blueprint pins the active timeline to batch_size and shows
        # the sweep view (plus one history view, to show what happens to a view
        # whose entities are not on the active timeline).
        bp = rrb.Blueprint(
            rrb.Horizontal(
                rrb.TimeSeriesView(
                    origin="/item_0/sweep",
                    name="train_time vs batch_size (batch_size timeline)",
                    axis_x=rrb.TimeAxis(
                        view_range=rdt.TimeRange(
                            start=rrb.TimeRangeBoundary.absolute(seq=min(batches) - 4),
                            end=rrb.TimeRangeBoundary.absolute(seq=max(batches) + 4),
                        )
                    ),
                ),
                ts_view("/item_0/batch_size=16", "history view on the same screen"),
            ),
            rrb.TimePanel(timeline="batch_size"),
            collapse_panels=True,
        )
        rr.send_blueprint(bp)

    rr.disconnect()
    return notes


def rrd_facts(path: Path):
    """(entities, timelines, timeline arrow types, has_blueprint) of a saved .rrd."""
    from rerun.experimental import RrdReader

    reader = RrdReader(str(path))
    has_bp = bool(reader.blueprints())
    entities: set[str] = set()
    timelines: dict[str, set[str]] = {}
    entity_timelines: dict[str, set[str]] = {}
    for store in reader.recordings():
        for chunk in reader.stream(store=store):
            # rerun escapes '=' in the string form of a path part; normalize.
            ent = str(chunk.entity_path).replace("\\", "")
            entities.add(ent)
            batch = chunk.to_record_batch()
            for field in batch.schema:
                if (field.metadata or {}).get(b"rerun:kind") != b"index":
                    continue
                timelines.setdefault(field.name, set()).add(str(field.type))
                entity_timelines.setdefault(ent, set()).add(field.name)
    return entities, timelines, entity_timelines, has_bp


CHECKS: list[tuple[str, bool, str]] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    CHECKS.append((name, ok, detail))
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}" + (f" — {detail}" if detail else ""))


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    res = run_history()
    ds = res.ds

    print("\n=== current machinery facts ===")
    print(f"dims: {dict(ds.sizes)}")
    print(f"over_time dtype: {ds['over_time'].dtype}")
    print(f"over_time coords: {[str(t)[:19] for t in ds['over_time'].values]}")
    print(res.regression_report.summary())

    check("over_time is a real datetime64 dim", str(ds["over_time"].dtype).startswith("datetime64"))
    check(
        "dims are input_vars + repeat + over_time",
        list(ds["train_time"].dims) == ["batch_size", "repeat", "over_time"],
        f"{ds['train_time'].dims}",
    )
    check("regression fired on train_time only",
          {r.variable: r.regressed for r in res.regression_report.results}
          == {"train_time": True, "accuracy": False})

    verdicts = replay_verdicts(res)
    v = verdicts["train_time"]
    check(
        "replay verdicts: train_time fails only at the last point",
        [t for t, bad, _ in v if bad] == [N_RUNS - 1],
        f"{[(t, bad) for t, bad, _ in v]}",
    )

    print("\n=== building recordings ===")
    notes = log_recording(res, verdicts, OUT_DIR / "history_regression.rrd", "report")
    log_recording(res, verdicts, OUT_DIR / "history_regression_noblueprint.rrd", "none")
    log_recording(res, verdicts, OUT_DIR / "history_regression_sweepmode.rrd", "sweep")
    for n in notes:
        print("  " + n)

    print("\n=== verifying recording ===")
    entities, timelines, entity_timelines, has_bp = rrd_facts(OUT_DIR / "history_regression.rrd")
    print(f"timelines: { {k: sorted(v) for k, v in timelines.items()} }")
    check("blueprint store present", has_bp)
    check(
        "named timelines: over_time (timestamp) + batch_size (sequence) coexist",
        "over_time" in timelines and "batch_size" in timelines,
        f"{sorted(timelines)}",
    )
    ot_types = timelines.get("over_time", set())
    check(
        "over_time timeline is timestamp-typed",
        any("timestamp" in t.lower() for t in ot_types),
        f"{sorted(ot_types)}",
    )
    both_share = all(
        any(ent.startswith(p) and "over_time" in tls for ent, tls in entity_timelines.items())
        for p in ("/item_0/batch_size", "/item_1/batch_size")
    )
    check("item_0 and item_1 entities share the over_time timeline", both_share)
    sweep_ents = {e: t for e, t in entity_timelines.items() if e.startswith("/item_0/sweep")}
    check(
        "sweep entity indexed on batch_size, not over_time",
        all("batch_size" in t and "over_time" not in t for t in sweep_ents.values()),
        f"{sweep_ents}",
    )
    check("regression overlay entities present",
          all(f"/item_2/overlay/{e}" in entities
              for e in ("history_mean", "baseline", "band_hi", "band_lo", "current")))

    _, _, _, nobp_has_bp = rrd_facts(OUT_DIR / "history_regression_noblueprint.rrd")
    check("no-blueprint copy carries no blueprint store", not nobp_has_bp)

    failed = [c for c in CHECKS if not c[1]]
    print(f"\n{len(CHECKS) - len(failed)}/{len(CHECKS)} checks passed")
    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
