name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: github-changelog-generator/github-changelog-generator@v1.16.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/changelog-config.yml
          
      - name: Commit changelog
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add CHANGELOG.md
            git commit -m "Update changelog"
            git push
          fi
