

name: Python Publish Workflow
on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  publish:
    name: Publish to PyPi
    needs: [build]
    uses: AsifArmanRahman/to-pypi-using-flit@v1
    with:
        password: ${{ secrets.PYPI_API_TOKEN }}  